### ISSUE TITLE
Friendly unit spawn point

### ISSUE THREAD

**Issue by iansui** [eye942/TbD#12]
![image](https://user-images.githubusercontent.com/29807447/121617493-eaf74980-ca19-11eb-92c7-0050a281242d.png)

Should the friendly units spawn at the bottom of the tower?
Right now they spawn at the center of the scene
There is no way to get rid of the enemy unit in the screenshot

**Comment by iansui** [comment]
#19 duplicate

**Comment by mathpop09** [comment]
done
