### ISSUE TITLE
Tower defense projectiles

### ISSUE THREAD

**Issue by eye942** [eye942/TbD#13]

**Comment by iansui** [comment]
![image](https://user-images.githubusercontent.com/29807447/121617810-8e485e80-ca1a-11eb-9d32-30ddce7c3e1e.png)

This is our current idea for the passive attack from the tower. There will be three different kinds of attack from different levels of the tower. If a level is destroyed by the enemy, the tower loses the ability to attack from that level

top level - long range arrows moving in a parabola curve
mid level - rocks or bombs
low level - melee

**Comment by iansui** [comment]
Added basic arrow & bomb attacks in #28
