### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by eye942** [eye942/TbD#36]
@iansui 
- [x] 1. Time spent before dying
- [x] 9. How long it takes for the tower to lose 75/50/25 HP
- [x] 10. How much mana is left when the game is over
- [x] 11. How much mana is used on spawning friendly unit(how much mana is consumed)

@eye942 
- [x] 3. How many units are deployed at any given time(counters for each type of unit)
- [x] 4. How much damage is done by passive projectiles
~~- [ ] 5. How much damage is done by local units~~

@vidhubala-selvaraj 
- [x] 2. How long it takes for fireballs to die
- [x] 6. Where do fireballs die
~~- [ ] 12. Track how many  fireballs are being destroyed in some constant time?~~

@CaptDirtyHarry 
- [x] 7. Where do friendly units die
- [x] 8. Where do enemy units die
- [x] 13. When do enemy units die

**Comment by iansui** [comment]
1.9.10.11 added in #51

**Comment by capthz** [comment]
7, 8, 13 added in #54

**Comment by eye942** [comment]
4 in #59

**Comment by eye942** [comment]
3 in #60
