### ISSUE TITLE
Fix ground unit clutter

### ISSUE THREAD

**Issue by eye942** [eye942/TbD#87]
- [ ] Enemy size/shape randomization
- [ ] Queue of enemies
- [ ] Instant combat resolution
- [ ] Add animation? (hopping blocks :P)
- [ ] Need art for better clarity. 
- [ ] Unit count cap

Choose 1 or more and implement

**Comment by iansui** [comment]
- smaller units are always rendered later than bigger units
- smaller units show up closer to the camera
